sudo: false
language: ruby
cache: bundler

rvm:
  - 1.9.3
  - 2.0.0
  - 2.2.0

bundler_args: --without integration
script:
  - bundle exec gem install rubygems-update
  - bundle exec update_rubygems
  - bundle exec rake
